version: 2.1
jobs:
  build_test:
    docker:
      - image:  circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
  build_docker_image:
    dcoker:
      image:  circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
        name: build Docker image
        command: |
          docker build -t node_learn -t appscrip/node_learn:latest  .
          echo $DOCKER_PASSWORD | docker login -u suryakant07 --password-stdin
          docker push suryakant07/node_learn:latest

workflows:
  build_test:
    jobs:
      - build_test
      - build_docker_image

