version: 2.1
jobs:
  build:
    docker:
      - image:  cimg/node@20.17.0
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
            npm run dev
  build_docker_image:
    docker:
      image:  cimg/node@20.17.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            docker build -t node_learn -t suryakant07/node_learn:latest  .
            echo $DOCKER_PASSWORD | docker login -u suryakant07 --password-stdin
            docker push suryakant07/node_learn:latest

workflows:
  build_now:
    jobs:
      - build
      - build_docker_image

